debug: true
letsencrypt: true
letsencryptEmail: 'kyuumeitai@gmail.com'
compress: true
baseDomain: 'featured.ltnext.com'
cors: false
updateChannel: 'stable'
traefikImage: false
traefikName: 'func_traefik'
traefikArgs: ['']
exoframeNetwork: 'func_functions'
publicKeysPath: '/root/.ssh'
plugins:
  install: ['exoframe-plugin-swarm']
  swarm:
    enabled: 'true'
    network: 'func_functions'