debug: true
letsencrypt: false
letsencryptEmail: kyuumeitai@gmail.com
compress: true
baseDomain: featured.ltnext.com
cors: false
updateChannel: stable
traefikImage: false
traefikName: exoframe
traefikArgs: []
exoframeNetwork: exoframe
publicKeysPath: /root/.ssh
plugins:
  install: []
