debug: false
letsencrypt: false
letsencryptEmail: kyuumeitai@gmail.com
compress: true
baseDomain: false
cors: false
updateChannel: stable
traefikImage: false
traefikName: exoframe
traefikArgs: []
exoframeNetwork: exoframe
publicKeysPath: /root/.ssh
plugins:
  install: []
